app/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('index');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = app()->errorHandler->error) {
            if (request()->isAjaxRequest) {
                echo $error['message'];
            } else {
                $this->render('error', $error);
            }
        }
    }

    /**
     * Displays the contact page.
     */
    public function actionContact()
    {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $name = '=?UTF-8?B?' . base64_encode($model->name) . '?=';
                $subject = '=?UTF-8?B?' . base64_encode($model->subject) . '?=';
                $headers = "From: $name <{$model->email}>\r\n" .
                    //"Reply-To: {$model->email}\r\n" .
                    "MIME-Version: 1.0\r\n" .
                    "Content-type: text/plain; charset=UTF-8";

                mail(param('adminEmail'), $subject, $model->body, $headers);
                user()->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    /**
     * Displays the maintenance page.
     */
    public function actionDown()
    {
        $this->layout = 'minimal';
        $this->render('down');
    }

    /**
     * Displays the login page.
     */
    public function actionLogin()
    {
        $this->layout = 'minimal';
        $model = new LoginForm;
        $this->performAjaxValidation($model, 'login-form');
        $request = request();
        if ($request->isPostRequest)
        {
            $model->attributes = $request->getPost('LoginForm');
            if ($model->validate() && $model->login())
            {
                /* @var $user WebUser */
                $user = user();
                $user->updateLastLoginAt();
                $this->redirect($user->returnUrl);
            }
        }
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        user()->logout();
        $this->redirect(app()->homeUrl);
    }



}

app/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	public $defaultAction = 'admin';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'postOnly + delete', // we only allow deletion via POST request
            array('auth.filters.AuthFilter'),
		);
	}


	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		//$profileAttr = array();
		if (!empty($model->profile)) {
			if (method_exists($model->profile,'detailData')) {
				$profileAttr = $model->profile->detailData($model);
			}
		}

		$this->render('view',array(
			'model'=> $model,
			//'profileAttr' => $profileAttr,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User('reg');



		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
			$model->attributes = $_POST['User'];



			//$transaction = Yii::app()->db->beginTransaction();
			if ($model->save()) {



				//$model->profile->user_id = $model->id;
				//if ($model->profile->save()) {
					//$transaction->commit();

					//$this->onUserCreate = array('Notifier', 'newUser');

					//$event = new CEvent($model);
					//$this->onUserCreate($event);

					//$this->redirect(array('view','id'=>$model->id));
				//} else {
					//$transaction->rollback();
					// т.к. пользователь сохранен - нужно сбросить все руками
					//$model->isNewRecord = true;
					//$model->password = '';
				//}
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function onUserCreate($event) {
		$this->raiseEvent('onUserCreate', $event);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		//if (!$model->profile) {$model->profile = new Profile();}
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
			$model->attributes=$_POST['User'];


			if ($model->save()) {
                $this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionReset($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
			$model->attributes=$_POST['User'];
			if ($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('reset',array(
				'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		} else {
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		//$model=new User('search');
		//$model->unsetAttributes();  // clear any default values

        $dataProvider = new CActiveDataProvider('User',
            array(
                'criteria'=>array(
                    //'with'=>array('profile'),
                    //'condition'=>'profile.roleId='.$status,
                ),


            ));

		/*if (isset($_GET['User'])) {
			$model->attributes=$_GET['User'];
		}*/

		$this->render('admin',array(
			'model'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}


	public function actionListTeacher() {
		$data = User::model()->getUserList(User::ROLE_TEACHER, 'teacherCosts.courseId = '. $_POST['Profile']['courseId']);
		echo CHtml::tag('option',
			array('value'=>''),CHtml::encode('-- выберите преподавателя --'),true);
		foreach($data as $index=>$model)
		{
			echo CHtml::tag('option',
				array('value'=>$model->id,'selected'=> $index == 0),CHtml::encode($model->name),true);
		}

	}

    public function actionForgot() {

        $model = new RecoveryForm;
        $this->performAjaxValidation($model, 'login-form');
        $request = request();

        if ($request->isPostRequest)
        {
            $model->attributes = $request->getPost('RecoveryForm');
            if ($model->validate())
            {
                //print_r($model);
                $criteria = new CDbCriteria;
                $criteria->compare('login', $model->login);
                //$criteria->with = array('profile');
                $user = User::model()->find($criteria);

                if($user) {
                    $passNew = $user->random_password();
                    $user->password = $passNew;

                    if($user->save()) {

                        $this->onPassReset = array('Notifier', 'resetPass');

                        $params = array("newPass" => $passNew);

                        $event = new CEvent($user, $params);
                        $this->onPassReset($event);

                        $this->render('recoverySuccess');
                    }


                }

            }
            else
                $this->render('recovery', array('model'=>$model));
        }
        else
            $this->render('recovery', array('model'=>$model));
    }

    public function onPassReset($event) {
        $this->raiseEvent('onPassReset', $event);
    }

    public function actionRegistration() {
        $model = new User('reg');

        // register event handlers
        //$model->onNewUser = array('Notifier','newUser');


        if (isset($_POST['User'])) {
            $model->setAttributes($_POST['User']);
            if ($model->save()) {

                $this->onUserCreate = array('Notifier', 'newUser');

                $event = new CEvent($model);
                $this->onUserCreate($event);

                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('success'));
            }

        }

        $this->render('registration', array( 'model' => $model));
    }

    public function actionSuccess() {
        $this->render('success');
    }
}

app/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form TbActiveForm */

$this->pageTitle = app()->name . ' - Contact';
$this->breadcrumbs = array(
    'Contact',
);
?>

    <h1>Contact</h1>

    <?php if (user()->hasFlash('contact')): ?>
        <?php $this->widget('bootstrap.widgets.TbAlert', array('alerts' => array('contact' => array()))); ?>
    <?php endif;?>



<div class="span4">
    <aside>
        <div class="widget">
            <h4><?=t('app', 'Get in touch with us')?></h4>
            <ul>
                <!--<li><label><strong><?/*=t('app', 'Phone : ')*/?></strong></label>
                    <p>
                        +900 888 707 123
                    </p>
                </li>-->
                <li><label><strong><?=t('app', 'Email : ')?></strong></label>
                    <p>
                        <a href="mailto:info@vyksaotzyvy.ru">info@vyksaotzyvy.ru</a>
                    </p>
                </li>
                <li><label><strong><?=t('app', 'Adress : ')?></strong></label>
                    <p>
                        Россия, Нижегородская область, Выкса
                    </p>
                </li>
            </ul>
        </div>
        <div class="widget">
            <h4><?=t('app', 'Social network')?></h4>
            <ul class="social-links">
                <li><a href="https://twitter.com/vyksaotzyvy" title="Twitter"><i class="icon-rounded icon-32 icon-twitter"></i></a></li>
                <li><a href="contact.html#" title="Facebook"><i class="icon-rounded icon-32 icon-facebook"></i></a></li>
                <li><a href="contact.html#" title="Google plus"><i class="icon-rounded icon-32 icon-google-plus"></i></a></li>
                <li><a href="contact.html#" title="Linkedin"><i class="icon-rounded icon-32 icon-linkedin"></i></a></li>
                <li><a href="contact.html#" title="Pinterest"><i class="icon-rounded icon-32 icon-pinterest"></i></a></li>
            </ul>
        </div>
    </aside>
</div>
<div class="span8">
    <div class="map-container">
        <script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=yJESvi6o_x7CuxzSYx9A92GEIq8PLfq6&width=600&height=450"></script>    </div>
    <div class="spacer30">
    </div>
    <?php $form = $this->beginWidget(
        'bootstrap.widgets.TbActiveForm',
        array(
            'id' => 'contact-form',
            'layout' => TbHtml::FORM_LAYOUT_HORIZONTAL,
            'enableClientValidation' => true,
            'clientOptions' => array(
                'validateOnSubmit' => true,
            ),
            'htmlOptions'=>array('class'=>'contact-form')
        )
    ); ?>


    <div class="row">
        <?php echo $form->errorSummary($model); ?>
        <div class="span3">
            <?php echo $form->labelEx($model, 'name'); ?>
            <?php echo $form->textField($model, 'name', array('class'=>'input-block-level', 'placeholder'=>'Your name')); ?>
        </div>
        <div class="span3">
            <?php echo $form->labelEx($model, 'email'); ?>
            <?php echo $form->textField($model, 'email', array('class'=>'input-block-level', 'placeholder'=>'Your email')); ?>
        </div>
        <div class="span6">
            <?php echo $form->labelEx($model, 'subject'); ?>
            <?php echo $form->textField($model, 'subject', array('class'=>'input-block-level', 'placeholder'=>'Your subject')); ?>
        </div>
        <div class="span8">
            <?php echo $form->labelEx($model, 'body'); ?>
            <?php echo $form->textArea($model, 'body', array('rows' => 9, 'class' => 'input-block-level', 'placeholder'=>'Your message')); ?>
            <?php echo TbHtml::submitButton('Submit', array('class' => 'btn btn-small btn-success')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>


</div>
</div>

app/views/site/down.php
<?php
/* @var SiteController $this */
?>
<div class="site-down">
    <?php $this->widget('bootstrap.widgets.TbHeroUnit', array(
        'heading' => 'Down for maintenance',
        'content' => app()->name . 'is temporarily unavailable due to planned maintenance.',
    )); ?>
</div>

app/views/site/error.php
<?php
/* @var SiteController $this */
/* @var array $error */
/* @var integer $code */
/* @var string $message */

$this->pageTitle = app()->name . ' - Error';
?>



<div class="span12">
    <div class="centered">
        <h2 class="error">404</h2>
        <h3>Sorry, that page doesn't exist!</h3>
        <p>
            The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.
        </p>
    </div>
</div>

app/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle = app()->name;
?>

<?php $this->beginWidget(
    'bootstrap.widgets.TbHeroUnit',
    array(
        'heading' => 'Welcome to ' . e(Yii::app()->name) . '<br />admin admin',
    )
); ?>

<p>Congratulations! You have successfully created your Yii application.</p>

<?php $this->endWidget(); ?>

<p>You may change the content of this page by modifying the following two files:</p>

<ul>
    <li>View file: <code><?php echo __FILE__; ?></code></li>
    <li>Layout file: <code><?php echo $this->getLayoutFile('main'); ?></code></li>
</ul>

<p>For more details on how to further develop this application, please read
    the <a href="http://www.yiiframework.com/doc/">documentation</a>.
    Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
    should you have any questions.</p>

app/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form TbActiveForm */

$this->pageTitle = app()->name . ' - Login';
?>
<div class="site-login">

    <h1><?php echo app()->name; ?></h1>

    <div class="login-form">

        <?php $form = $this->beginWidget(
            'bootstrap.widgets.TbActiveForm',
            array(
                'id' => 'login-form',
            )
        ); ?>

        <fieldset>
            <?php echo $form->textFieldControlGroup(
                $model,
                'username',
                array('block' => true, 'label' => false, 'placeholder' => t('app', 'username'))
            ); ?>


            <?php echo $form->passwordFieldControlGroup(
                $model,
                'password',
                array('block' => true, 'label' => false, 'placeholder' => t('app', 'password'))
            ); ?>

        </fieldset>

        <?php
            echo CHtml::link(t('app', 'Forgot your password?'),array('user/forgot'));
        ?>

        <?php echo TbHtml::submitButton(
            t('app','Enter'),
            array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'size' => TbHtml::BUTTON_SIZE_LARGE, 'block' => true)
        ); ?>

        <?php $this->endWidget(); ?>

    </div>
</div>