app/controllers/ImagesController.php
<?php

class ImagesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
            array('auth.filters.AuthFilter'),
			'postOnly + delete', // we only allow deletion via POST request


		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Images;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Images'])) {
			$model->attributes=$_POST['Images'];
			if ($model->save()) {
				$this->redirect(array('view', 'id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Images'])) {
			$model->attributes=$_POST['Images'];
			if ($model->save()) {
				$this->redirect(array('index'));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		} else {
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new Images('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['Images'])) {
			$model->attributes=$_GET['Images'];
		}

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Images the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Images::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}

    public function actionList($order = null)
    {

        $model = new Images();



        $this->render('list', compact('model'));
    }

    public function actionView($id) {

        $model = $this->loadModel($id);

        $comment = new Comment();
        $comment->images_id = $model->id;

        if(Yii::app()->user->id)
            $comment->user_id = Yii::app()->user->id;

        $this->render('view', compact('model','comment'));
    }

}

app/views/images/_form.php
<?php
/* @var $this ImagesController */
/* @var $model Images */
/* @var $form TbActiveForm */
?>

<div class="form">

    <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'images-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
    'htmlOptions'=>array('enctype' => 'multipart/form-data')
)); ?>



    <?php echo $form->errorSummary($model); ?>

            <?php //echo$form->textFieldControlGroup($model,'id',array('span'=>5)); ?>

            <?php //echo$form->textFieldControlGroup($model,'photo',array('span'=>5,'maxlength'=>255));
                echo $form->fileFieldControlGroup($model, 'photo');
                if($model->photo) echo CHtml::image(baseUrl().'uploads/'.$model->photo);
            ?>

            <?php echo$form->textFieldControlGroup($model,'description',array('span'=>5,'maxlength'=>255)); ?>

            <?php //echo$form->textFieldControlGroup($model,'rating',array('span'=>5)); ?>

            <?php //echo$form->textFieldControlGroup($model,'created',array('span'=>5)); ?>

            <?php //echo$form->textFieldControlGroup($model,'modified',array('span'=>5)); ?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton($model->isNewRecord ? t('app', 'Create') : t('app','Save'),array(
		    'color'=>TbHtml::BUTTON_COLOR_PRIMARY,
		    'size'=>TbHtml::BUTTON_SIZE_LARGE,
		)); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

app/views/images/_list.php
<?php
/* @var $this ImagesController */
/* @var $model Images */



?>

<li class="span3">
    <div class="thumbnail">
        <?php echo CHtml::image(baseUrl().'uploads/'.$data->photo, 'sdf' ,array('style'=>'width:300px;height:200px') );?>

        <div class="caption">

            <p><?=$data->description;?></p>
            <p><?=$data->ShowRating ?> </p>
            <?php echo CHtml::link(t('app','Comment'),array('images/view', 'id'=>$data->id))?>
        </div>
    </div>
</li>

app/views/images/_search.php
<?php
/* @var $this ImagesController */
/* @var $model Images */
/* @var $form CActiveForm */
?>

<div class="wide form">

    <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

                    <?php echo $form->textFieldControlGroup($model,'id',array('span'=>5)); ?>

                    <?php echo $form->textFieldControlGroup($model,'photo',array('span'=>5,'maxlength'=>255)); ?>

                    <?php echo $form->textFieldControlGroup($model,'description',array('span'=>5,'maxlength'=>255)); ?>

                    <?php echo $form->textFieldControlGroup($model,'rating',array('span'=>5)); ?>

                    <?php echo $form->textFieldControlGroup($model,'created',array('span'=>5)); ?>

                    <?php echo $form->textFieldControlGroup($model,'modified',array('span'=>5)); ?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton('Search',  array('color' => TbHtml::BUTTON_COLOR_PRIMARY,));?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- search-form -->

app/views/images/create.php
<?php
/* @var $this ImagesController */
/* @var $model Images */
?>

<?php
$this->breadcrumbs=array(
	Yii::t('app', 'Images')=>array('/'),
	Yii::t('app', 'Create'),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List Images'), 'url'=>array('index')),
);
?>

<h1><?php echo Yii::t('app','Create Images'); ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

app/views/images/index.php
<?php
/* @var $this ImagesController */
/* @var $model Images */


$this->breadcrumbs=array(
	Yii::t('app', 'Images')
);

$this->menu=array(
	array('label'=>Yii::t('app', 'Create Images'), 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#images-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app','Manage Images'); ?></h1>

<?php echo CHtml::link(Yii::t('app', 'Advanced Search'),'#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'images-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'photo',
		'description',
		'rating',
		'created',
		'modified',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{update}{delete}',
		),
	),
)); ?>

app/views/images/list.php
<?php
/* @var $this ImagesController */
/* @var $model Images */


$this->pageTitle = 'Последние добавленые фото';

$this->breadcrumbs=array(
    Yii::t('app', 'Images')=>array('/')
);

$this->menu=array();
?>

    <h1><?php echo Yii::t('app','Last Create Images'); ?></h1>

    <div class="thumbnails">
        <?php $this->widget('zii.widgets.CListView', array(
            'dataProvider'=>$model->search(),
            'itemView'=>'_list',
            'sortableAttributes'=>array(
                'rating',
            ),
            //'template'=>'{items} {pager}',
        ));?>
    </div>

app/views/images/update.php
<?php
/* @var $this ImagesController */
/* @var $model Images */
?>

<?php
$this->breadcrumbs=array(
	Yii::t('app', 'Images')=>array('index'),
	Yii::t('app', 'Update'),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List Images'), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create Images'), 'url'=>array('create')),
);
?>

    <h1><?php Yii::t('app', 'Update Images');?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

app/views/images/view.php
<?php
/* @var $this ImagesController */
/* @var $model Images */

$this->pageTitle = 'Последние добавленые фото';

$this->breadcrumbs=array(
    Yii::t('app', 'Images')=>array('/'),
    t('app', 'view')
);

$this->menu=array();
?>

<h1><?php echo Yii::t('app','Photo comment'); ?></h1>

<div class="row">
    <div class="span4"><?php echo  CHtml::image(baseUrl().'uploads/'.$model->photo, '' ,array('style'=>'width:300px;height:200px') );?></div>
    <div class="span4">
        <p><strong>Рейтинг:</strong> <?=$model->ShowRating ?> </p>
        <?
            if($model->description)
                echo "<p><strong>Описание:</strong> $model->description</p>";
        ?>

    </div>
</div>


    <h4 class="anchor" id="comment"><?=t('app','Comments')?></h4>
<? if (!empty($model->comments)) {
    $this->widget('zii.widgets.CListView', array(
        'dataProvider'=> new CActiveDataProvider('Comment',array(
                'data'=>$model->comments,
            )),
        'itemView'=>'//comment/_view',
        'template'=>'{items}',
    ));
} else {?>
    <p><i><?=t('app', 'Comment not found')?></i></p>
<?}?>


    <h4 class="anchor" id="comment"><?=t('app','Add Comments')?></h4>
<?php

$this->renderPartial('/comment/_formComment', array('model'=>$comment));

?>