app/controllers/ImagesController.php
<?php

class ImagesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
            array('auth.filters.AuthFilter'),
			'postOnly + delete', // we only allow deletion via POST request


		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Images;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Images'])) {
			$model->attributes=$_POST['Images'];
			if ($model->save()) {
				$this->redirect(array('view', 'id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Images'])) {
			$model->attributes=$_POST['Images'];
			if ($model->save()) {
				$this->redirect(array('index'));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		} else {
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new Images('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['Images'])) {
			$model->attributes=$_GET['Images'];
		}

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Images the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Images::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}

    public function actionList($order = null)
    {

        $model = new Images();



        $this->render('list', compact('model'));
    }

    public function actionView($id) {

        $model = $this->loadModel($id);

        $comment = new Comment();
        $comment->images_id = $model->id;

        if(Yii::app()->user->id)
            $comment->user_id = Yii::app()->user->id;

        $this->render('view', compact('model','comment'));
    }

}

app/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	public $defaultAction = 'admin';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'postOnly + delete', // we only allow deletion via POST request
            array('auth.filters.AuthFilter'),
		);
	}


	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		//$profileAttr = array();
		if (!empty($model->profile)) {
			if (method_exists($model->profile,'detailData')) {
				$profileAttr = $model->profile->detailData($model);
			}
		}

		$this->render('view',array(
			'model'=> $model,
			//'profileAttr' => $profileAttr,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User('reg');



		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
			$model->attributes = $_POST['User'];



			//$transaction = Yii::app()->db->beginTransaction();
			if ($model->save()) {



				//$model->profile->user_id = $model->id;
				//if ($model->profile->save()) {
					//$transaction->commit();

					//$this->onUserCreate = array('Notifier', 'newUser');

					//$event = new CEvent($model);
					//$this->onUserCreate($event);

					//$this->redirect(array('view','id'=>$model->id));
				//} else {
					//$transaction->rollback();
					// т.к. пользователь сохранен - нужно сбросить все руками
					//$model->isNewRecord = true;
					//$model->password = '';
				//}
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function onUserCreate($event) {
		$this->raiseEvent('onUserCreate', $event);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		//if (!$model->profile) {$model->profile = new Profile();}
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
			$model->attributes=$_POST['User'];


			if ($model->save()) {
                $this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionReset($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['User'])) {
			$model->attributes=$_POST['User'];
			if ($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('reset',array(
				'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		} else {
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		//$model=new User('search');
		//$model->unsetAttributes();  // clear any default values

        $dataProvider = new CActiveDataProvider('User',
            array(
                'criteria'=>array(
                    //'with'=>array('profile'),
                    //'condition'=>'profile.roleId='.$status,
                ),


            ));

		/*if (isset($_GET['User'])) {
			$model->attributes=$_GET['User'];
		}*/

		$this->render('admin',array(
			'model'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}


	public function actionListTeacher() {
		$data = User::model()->getUserList(User::ROLE_TEACHER, 'teacherCosts.courseId = '. $_POST['Profile']['courseId']);
		echo CHtml::tag('option',
			array('value'=>''),CHtml::encode('-- выберите преподавателя --'),true);
		foreach($data as $index=>$model)
		{
			echo CHtml::tag('option',
				array('value'=>$model->id,'selected'=> $index == 0),CHtml::encode($model->name),true);
		}

	}

    public function actionForgot() {

        $model = new RecoveryForm;
        $this->performAjaxValidation($model, 'login-form');
        $request = request();

        if ($request->isPostRequest)
        {
            $model->attributes = $request->getPost('RecoveryForm');
            if ($model->validate())
            {
                //print_r($model);
                $criteria = new CDbCriteria;
                $criteria->compare('login', $model->login);
                //$criteria->with = array('profile');
                $user = User::model()->find($criteria);

                if($user) {
                    $passNew = $user->random_password();
                    $user->password = $passNew;

                    if($user->save()) {

                        $this->onPassReset = array('Notifier', 'resetPass');

                        $params = array("newPass" => $passNew);

                        $event = new CEvent($user, $params);
                        $this->onPassReset($event);

                        $this->render('recoverySuccess');
                    }


                }

            }
            else
                $this->render('recovery', array('model'=>$model));
        }
        else
            $this->render('recovery', array('model'=>$model));
    }

    public function onPassReset($event) {
        $this->raiseEvent('onPassReset', $event);
    }

    public function actionRegistration() {
        $model = new User('reg');

        // register event handlers
        //$model->onNewUser = array('Notifier','newUser');


        if (isset($_POST['User'])) {
            $model->setAttributes($_POST['User']);
            if ($model->save()) {

                $this->onUserCreate = array('Notifier', 'newUser');

                $event = new CEvent($model);
                $this->onUserCreate($event);

                if (Yii::app()->getRequest()->getIsAjaxRequest())
                    Yii::app()->end();
                else
                    $this->redirect(array('success'));
            }

        }

        $this->render('registration', array( 'model' => $model));
    }

    public function actionSuccess() {
        $this->render('success');
    }
}

app/views/layouts/_footer.php
<div id="footer">
	<p class="pull-right">Copyright &copy; <?php echo date('Y'); ?>, разработка <a href="">Personal System</a></p>
</div>

app/views/layouts/_head.php
<?php
/* @var Controller $this */
?>
<head>
	<base href="<? echo Yii::app()->baseUrl;?>/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="language" content="en"/>
    <link rel="icon" href="<?php echo baseUrl('/favicon.ico'); ?>" type="image/x-icon"/>
    <title><?php echo e($this->pageTitle); ?></title>
    <?php css('css/main.css'); ?>
    <?php css('css/responsive.css'); ?>
    <?php css('css/style.css'); ?>
	<?php css('css/_schedule.css'); ?>
    <?php js('js/main.js'); ?>
    <?php js('js/schedule.js'); ?>
    <?php app()->bootstrap->registerAllScripts(); ?>
    <?php app()->bootstrap->registerYiistrapCss(); ?>
</head>

app/views/layouts/_nav.php
<?php $this->widget(
	'bootstrap.widgets.TbNavbar', array(
		'color' => TbHtml::NAVBAR_COLOR_INVERSE,
		'brandLabel' => Yii::app()->user->getState('organization'),
		'collapse' => true,
		'items' => array(
			array(
				'class' => 'bootstrap.widgets.TbNav',
				'items' => array(
                    array('label'=> 'Зарегистрироваться','url'=>array('/user/registration'),'visible'=>Yii::app()->user->isGuest),
                    array('label'=> 'Добавить фото', 'url'=> array('/images/create'),'visible'=>!Yii::app()->user->isGuest)
				)
			),
			array(
				'class' => 'bootstrap.widgets.TbNav',
				'items' => array(
                    array('label' => 'Пользователи', 'url' => array('/user'), 'visible' => user()->isAdmin),
                    array('label' => 'Роли', 'url' => array('/auth'), 'visible' => user()->isAdmin),
					array('label' => 'Войти', 'url' => array('/site/login'), 'visible' => user()->isGuest),
					array(
						'label' => 'Выйти ('.user()->name.')',
						'url' => array('/site/logout'),
						'visible' => !user()->isGuest
					)

				)
			)
		)
	)
); ?>


<?php /*$this->widget(
	'bootstrap.widgets.TbNavbar',
	array(
		'collapse' => true,
		'items' => array(
			array(
				'class' => 'bootstrap.widgets.TbNav',
				'items' => array(
					array('label' => 'Объекты', 'url' => array('/object/index')),
					array('label' => 'Категории', 'url' => array('/category/admin'),  'visible' => user()->isAdmin ),
					array('label' => 'Contact', 'url' => array('/site/contact')),
					array('label' => 'Login', 'url' => array('/site/login'), 'visible' => user()->isGuest),
					array(
						'label' => 'Logout (' . user()->name . ')',
						'url' => array('/site/logout'),
						'visible' => !user()->isGuest
					)
				),
			),
		),
	)
); */
?>

app/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html lang="en">
<?php $this->renderPartial('app.views.layouts._head'); ?>
<body class="layout-main">

<?php $this->renderPartial('app.views.layouts._nav'); ?>

<div class="container" id="page">

    <?php if (!empty($this->breadcrumbs)): ?>
        <?php $this->widget(
            'bootstrap.widgets.TbBreadcrumb',
            array(
                'links' => $this->breadcrumbs,
            )
        ); ?>
    <?php endif ?>

	<div class="container">
		<div class="row">
			<div class="span9">
				<?php echo $content; ?>
			</div>
			<div class="span3">
				<div id="sidebar">

					<?php $this->widget('bootstrap.widgets.TbNav', array(
						'type' => TbHtml::NAV_TYPE_TABS,
						'stacked' => true,
						'items' => $this->menu,

					)); ?>
				</div>
				<!-- sidebar -->
			</div>
		</div>

	</div>



	<hr/>
	<?php $this->renderPartial('app.views.layouts._footer'); ?>

</div>
</body>
</html>

app/views/layouts/email.php
<?php
/* @var Controller $this */
?>
<!DOCTYPE html>
<!--suppress HtmlUnknownAttribute -->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="language" content="en"/>

    <link rel="icon" href="<?php echo baseUrl('/favicon.ico'); ?>" type="image/x-icon"/>

    <title><?php echo e($this->pageTitle); ?></title>
</head>

<body class="layout-email" bgcolor="#EEEEEE"
      style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #333333; padding: 80px 0;">

<table border="0" cellspacing="0" cellpadding="0" width="100%" align="center" style="table-layout: fixed;">
    <tr>
        <td valign="top">
            <table width="670" border="0" cellspacing="0" cellpadding="0" align="center">
                <tr>
                    <td valign="top">
                        <div align="right" style="margin-bottom: 5px;">
                            <a href="{viewUrl}" style="text-decoration: none;"><?php echo t(
                                    'email',
                                    'Read this in your browser'
                                ); ?>.</a>
                        </div>
                    </td>
                </tr>
            </table>
            <table width="670" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#FFFFFF"
                   style="-webkit-border-radius: 6px; -moz-border-radius: 6px; border-radius: 6px;">
                <tr>
                    <td valign="top">
                        <div style="padding: 20px; text-align: left;">
                            <?php echo $content; ?>
                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>
</html>

app/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html lang="en">
<?php $this->renderPartial('app.views.layouts._head'); ?>
<body class="layout-main">
<?php $this->renderPartial('app.views.layouts._nav'); ?>

<div class="container" id="page">

    <?php if (!empty($this->breadcrumbs)): ?>
        <?php $this->widget(
            'bootstrap.widgets.TbBreadcrumb',
            array(
                'links' => $this->breadcrumbs,
            )
        ); ?>
    <?php endif ?>

	<div class="container">
		<div class="row">
			<div class="span12">
				<?php echo $content; ?>
			</div>
		</div>

	</div>



    <hr/>
	<?php $this->renderPartial('app.views.layouts._footer'); ?>

</div>
</body>
</html>

app/views/layouts/minimal.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html lang="en">
<?php $this->renderPartial('app.views.layouts._head'); ?>
<body class="layout-minimal">

<div class="container">
    <?php echo $content; ?>
</div>

</body>
</html>